USE Bookstore

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE name='Users' AND xtype='U')
	CREATE TABLE Users(
		UserId		INT IDENTITY(1,1)	NOT NULL,
		Name		VARCHAR(100)		NOT NULL,
		Email		VARCHAR(100)		NOT NULL,
		Password	VARCHAR(200)			NULL,
		IsAdmin		BIT					NOT NULL,
		CreatedAt	DATETIME			NOT NULL,
		UpdatedAt	DATETIME			NOT NULL

		CONSTRAINT PK_User PRIMARY KEY (UserId)
	)
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE name='Genre' AND xtype='U')
	CREATE TABLE Genre(
		GenreId		INT IDENTITY(1,1)	NOT NULL,
		Name		VARCHAR(100)		NOT NULL,
		CreatedAt	DATETIME			NOT NULL,
		UpdatedAt	DATETIME			NOT NULL

		CONSTRAINT PK_Genre PRIMARY KEY (GenreId)
	)
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE name='Book' AND xtype='U')
	CREATE TABLE Book(
		BookId			INT IDENTITY(1,1)	NOT NULL,
		GenreId			INT					NOT NULL,
		Name			VARCHAR(100)		NOT NULL,
		Description		VARCHAR(500)		NOT NULL,
		ImagePath		VARCHAR(100)		NOT NULL,
		ImageName		VARCHAR(100)		NOT NULL,
		ImageAlt		VARCHAR(100)		NOT NULL,
		CreatedAt		DATETIME			NOT NULL,
		UpdatedAt		DATETIME			NOT NULL

		CONSTRAINT PK_Book PRIMARY KEY (BookId),
		FOREIGN KEY (GenreId) REFERENCES Genre(GenreId)
	)
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE name='UserBook' AND xtype='U')
	CREATE TABLE UserBook(
		UserBookId		INT IDENTITY(1,1)	NOT NULL,
		UserId			INT					NOT NULL,
		BookId			INT					NOT NULL,
		AcquiredAt		DATETIME			NOT NULL

		CONSTRAINT PK_UserBook PRIMARY KEY (UserBookId),
		FOREIGN KEY (UserId) REFERENCES Users(UserId),
		FOREIGN KEY (BookId) REFERENCES Book(BookId)
	)
GO
